/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PlatformRouteRouteImport } from './routes/_platform/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated/scripts'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedTimeRouteImport } from './routes/_authenticated/time'
import { Route as AuthenticatedDevicesIdRouteImport } from './routes/_authenticated/devices.$id'
import { Route as AuthenticatedTicketsIdRouteImport } from './routes/_authenticated/tickets.$id'
import { Route as PlatformPlatformIndexRouteImport } from './routes/_platform/platform/index'
import { Route as PlatformPlatformWorkspacesIndexRouteImport } from './routes/_platform/platform/workspaces.index'
import { Route as PlatformPlatformWorkspacesIdRouteImport } from './routes/_platform/platform/workspaces.$id'
import { Route as ApiPublicAgentCheckinRouteImport } from './routes/api/public/agent/checkin'
import { Route as ApiPublicAgentEnrollRouteImport } from './routes/api/public/agent/enroll'
import { Route as ApiPublicAgentResultRouteImport } from './routes/api/public/agent/result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimeRoute = AuthenticatedTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesIdRoute = AuthenticatedDevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDevicesRoute,
} as any)
const AuthenticatedTicketsIdRoute = AuthenticatedTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTicketsRoute,
} as any)
const PlatformPlatformIndexRoute = PlatformPlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformPlatformWorkspacesIndexRoute =
  PlatformPlatformWorkspacesIndexRouteImport.update({
    id: '/platform/workspaces/',
    path: '/platform/workspaces/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformPlatformWorkspacesIdRoute =
  PlatformPlatformWorkspacesIdRouteImport.update({
    id: '/platform/workspaces/$id',
    path: '/platform/workspaces/$id',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const ApiPublicAgentCheckinRoute = ApiPublicAgentCheckinRouteImport.update({
  id: '/api/public/agent/checkin',
  path: '/api/public/agent/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentEnrollRoute = ApiPublicAgentEnrollRouteImport.update({
  id: '/api/public/agent/enroll',
  path: '/api/public/agent/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentResultRoute = ApiPublicAgentResultRouteImport.update({
  id: '/api/public/agent/result',
  path: '/api/public/agent/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/scripts': typeof AuthenticatedScriptsRoute
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/time': typeof AuthenticatedTimeRoute
  '/devices/$id': typeof AuthenticatedDevicesIdRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/platform/': typeof PlatformPlatformIndexRoute
  '/platform/workspaces/$id': typeof PlatformPlatformWorkspacesIdRoute
  '/api/public/agent/checkin': typeof ApiPublicAgentCheckinRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/result': typeof ApiPublicAgentResultRoute
  '/platform/workspaces/': typeof PlatformPlatformWorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/scripts': typeof AuthenticatedScriptsRoute
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/time': typeof AuthenticatedTimeRoute
  '/devices/$id': typeof AuthenticatedDevicesIdRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/platform': typeof PlatformPlatformIndexRoute
  '/platform/workspaces/$id': typeof PlatformPlatformWorkspacesIdRoute
  '/api/public/agent/checkin': typeof ApiPublicAgentCheckinRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/result': typeof ApiPublicAgentResultRoute
  '/platform/workspaces': typeof PlatformPlatformWorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_platform': typeof PlatformRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/_authenticated/scripts': typeof AuthenticatedScriptsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/_authenticated/time': typeof AuthenticatedTimeRoute
  '/_authenticated/devices/$id': typeof AuthenticatedDevicesIdRoute
  '/_authenticated/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/_platform/platform/': typeof PlatformPlatformIndexRoute
  '/_platform/platform/workspaces/$id': typeof PlatformPlatformWorkspacesIdRoute
  '/api/public/agent/checkin': typeof ApiPublicAgentCheckinRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/result': typeof ApiPublicAgentResultRoute
  '/_platform/platform/workspaces/': typeof PlatformPlatformWorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/billing'
    | '/clients'
    | '/dashboard'
    | '/devices'
    | '/scripts'
    | '/tickets'
    | '/time'
    | '/devices/$id'
    | '/tickets/$id'
    | '/platform/'
    | '/platform/workspaces/$id'
    | '/api/public/agent/checkin'
    | '/api/public/agent/enroll'
    | '/api/public/agent/result'
    | '/platform/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alerts'
    | '/billing'
    | '/clients'
    | '/dashboard'
    | '/devices'
    | '/scripts'
    | '/tickets'
    | '/time'
    | '/devices/$id'
    | '/tickets/$id'
    | '/platform'
    | '/platform/workspaces/$id'
    | '/api/public/agent/checkin'
    | '/api/public/agent/enroll'
    | '/api/public/agent/result'
    | '/platform/workspaces'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_platform'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/billing'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/scripts'
    | '/_authenticated/tickets'
    | '/_authenticated/time'
    | '/_authenticated/devices/$id'
    | '/_authenticated/tickets/$id'
    | '/_platform/platform/'
    | '/_platform/platform/workspaces/$id'
    | '/api/public/agent/checkin'
    | '/api/public/agent/enroll'
    | '/api/public/agent/result'
    | '/_platform/platform/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAgentCheckinRoute: typeof ApiPublicAgentCheckinRoute
  ApiPublicAgentEnrollRoute: typeof ApiPublicAgentEnrollRoute
  ApiPublicAgentResultRoute: typeof ApiPublicAgentResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time': {
      id: '/_authenticated/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AuthenticatedTimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices/$id': {
      id: '/_authenticated/devices/$id'
      path: '/$id'
      fullPath: '/devices/$id'
      preLoaderRoute: typeof AuthenticatedDevicesIdRouteImport
      parentRoute: typeof AuthenticatedDevicesRoute
    }
    '/_authenticated/tickets/$id': {
      id: '/_authenticated/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AuthenticatedTicketsIdRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_platform/platform/': {
      id: '/_platform/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformPlatformIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/platform/workspaces/': {
      id: '/_platform/platform/workspaces/'
      path: '/platform/workspaces'
      fullPath: '/platform/workspaces/'
      preLoaderRoute: typeof PlatformPlatformWorkspacesIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/platform/workspaces/$id': {
      id: '/_platform/platform/workspaces/$id'
      path: '/platform/workspaces/$id'
      fullPath: '/platform/workspaces/$id'
      preLoaderRoute: typeof PlatformPlatformWorkspacesIdRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/api/public/agent/checkin': {
      id: '/api/public/agent/checkin'
      path: '/api/public/agent/checkin'
      fullPath: '/api/public/agent/checkin'
      preLoaderRoute: typeof ApiPublicAgentCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/enroll': {
      id: '/api/public/agent/enroll'
      path: '/api/public/agent/enroll'
      fullPath: '/api/public/agent/enroll'
      preLoaderRoute: typeof ApiPublicAgentEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/result': {
      id: '/api/public/agent/result'
      path: '/api/public/agent/result'
      fullPath: '/api/public/agent/result'
      preLoaderRoute: typeof ApiPublicAgentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDevicesRouteChildren {
  AuthenticatedDevicesIdRoute: typeof AuthenticatedDevicesIdRoute
}

const AuthenticatedDevicesRouteChildren: AuthenticatedDevicesRouteChildren = {
  AuthenticatedDevicesIdRoute: AuthenticatedDevicesIdRoute,
}

const AuthenticatedDevicesRouteWithChildren =
  AuthenticatedDevicesRoute._addFileChildren(AuthenticatedDevicesRouteChildren)

interface AuthenticatedTicketsRouteChildren {
  AuthenticatedTicketsIdRoute: typeof AuthenticatedTicketsIdRoute
}

const AuthenticatedTicketsRouteChildren: AuthenticatedTicketsRouteChildren = {
  AuthenticatedTicketsIdRoute: AuthenticatedTicketsIdRoute,
}

const AuthenticatedTicketsRouteWithChildren =
  AuthenticatedTicketsRoute._addFileChildren(AuthenticatedTicketsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRouteWithChildren
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRouteWithChildren
  AuthenticatedTimeRoute: typeof AuthenticatedTimeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRouteWithChildren,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRouteWithChildren,
  AuthenticatedTimeRoute: AuthenticatedTimeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlatformRouteRouteChildren {
  PlatformPlatformIndexRoute: typeof PlatformPlatformIndexRoute
  PlatformPlatformWorkspacesIdRoute: typeof PlatformPlatformWorkspacesIdRoute
  PlatformPlatformWorkspacesIndexRoute: typeof PlatformPlatformWorkspacesIndexRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformPlatformIndexRoute: PlatformPlatformIndexRoute,
  PlatformPlatformWorkspacesIdRoute: PlatformPlatformWorkspacesIdRoute,
  PlatformPlatformWorkspacesIndexRoute: PlatformPlatformWorkspacesIndexRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAgentCheckinRoute: ApiPublicAgentCheckinRoute,
  ApiPublicAgentEnrollRoute: ApiPublicAgentEnrollRoute,
  ApiPublicAgentResultRoute: ApiPublicAgentResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
